Repository mehrdadhalali/Games-Release-Tracker, pull requests merged in 2024-10, with the labels that each got.

#19 Created new folders with README files for each.
  dashboard/README.md
  load_to_rds/README.md
  report/README.md
  schema/README.md
  terraform/README.md
  web_scraping/epic_games_scraper/README.md
  web_scraping/gog_scraper/README.md
  web_scraping/steam_scraper/README.md
Labels: documentation

#20 Set up a basic workflow
  .github/workflows/dashboard.yml
  .github/workflows/extract.yml
  .github/workflows/load.yml
  .github/workflows/main.yml
  .github/workflows/report.yml
  .github/workflows/requirements.txt
  dashboard/requirements.txt
  dashboard/test_dashboard.py
  load_to_rds/requirements.txt
  load_to_rds/test_load_to_rds.py
  report/requirements.txt
  report/test_report.py
  web_scraping/epic_games_scraper/requirements.txt
  web_scraping/epic_games_scraper/test_epic_games.py
  web_scraping/gog_scraper/requirements.txt
  web_scraping/gog_scraper/test_gog.py
  web_scraping/steam_scraper/requirements.txt
  web_scraping/steam_scraper/test_steam.py
Labels: feature

#21 Fixed workflows.
  .github/workflows/extract.yml
  .github/workflows/load.yml
  .github/workflows/report.yml
Labels: enhancement

#38 Set-up requirements and main file for Steam scraper.
  web_scraping/steam_scraper/requirements.txt
  web_scraping/steam_scraper/scrape_steam.py
  web_scraping/steam_scraper/test_scrape_steam.py
Labels: enhancement

#34 Testing the new yml file for extract only does one check.
  .github/workflows/dashboard.yml
  .github/workflows/extract.yml
  .github/workflows/load.yml
  .github/workflows/report.yml
Labels: enhancement

#41 terraform for rds
  .gitignore
  terraform/README.md
  terraform/main.tf
  terraform/outputs.tf
  terraform/variables.tf
Labels: enhancement

#45 PR - Steam scraper initial functions
  web_scraping/steam_scraper/scrape_steam.py
  web_scraping/steam_scraper/test_scrape_steam.py
Labels: feature

#43 Added wireframe to readme
  dashboard/README.md
  dashboard/wireframe_about.png
  dashboard/wireframe_dashboard.png
  dashboard/wireframe_subscribe.png
Labels: documentation

#51 Added pages structure to dashboard
  dashboard/dashboard.py
  dashboard/pages/about.py
  dashboard/pages/subscribe.py
  dashboard/requirements.txt
  dashboard/sl_queries.py
Labels: feature

#53 PR - Extract steam scrape
  web_scraping/steam_scraper/scrape_steam.py
  web_scraping/steam_scraper/test_scrape_steam.py
Labels: enhancement

#61 Dark theme and monospace
  dashboard/.streamlit/config.toml
  dashboard/dashboard.py
Labels: enhancement

#63 Create schema - PR
  ERD.png
  schema/README.md
  schema/connect.sh
  schema/reset.sh
  schema/schema.sql
  terraform/README.md
Labels: documentation, enhancement

#64 Extract scrape steam
  web_scraping/steam_scraper/lambda_handler.py
  web_scraping/steam_scraper/scrape_steam.py
Labels: enhancement, feature

#58 Extract gog mehrdad
  web_scraping/gog_scraper/README.md
  web_scraping/gog_scraper/lambda_handler.py
  web_scraping/gog_scraper/requirements.txt
  web_scraping/gog_scraper/scrape_gog.py
  web_scraping/gog_scraper/scrape_gog_game.py
  web_scraping/gog_scraper/test_gog.py
  web_scraping/gog_scraper/test_scrape_gog.py
Labels: enhancement, feature

#69 Dashboard about paula
  dashboard/pages/about.py
  dashboard/pages/logo.png
Labels: enhancement

#67 Dockerised steam scraper
  web_scraping/steam_scraper/Dockerfile
  web_scraping/steam_scraper/lambda_handler.py
  web_scraping/steam_scraper/push-to-ecr.sh
Labels: enhancement

#71 Img path fixed
  dashboard/pages/about.py
Labels: bug

#80 Dashboard graphs paula
  dashboard/dashboard.py
  dashboard/pages/subscribe.py
Labels: feature

#82 Bug Fix and README improvement.
  web_scraping/steam_scraper/README.md
  web_scraping/steam_scraper/lambda_handler.py
  web_scraping/steam_scraper/scrape_steam.py
Labels: bug, documentation

#95 Set up folder structure for starting work with report generation.
  report/database_handler.py
  report/email_report.py
  report/generate_report.py
  report/requirements.txt
Labels: enhancement

#88 Terraform create scrape lambdas
  terraform/README.md
  terraform/main.tf
Labels: enhancement

#100 ERD and Schema changed - No listing_date
  ERD.png
  schema/schema.sql
Labels: documentation

#103 Changed date formating to match scrape convention.
  web_scraping/steam_scraper/scrape_steam.py
Labels: bug

#102 Dashboard graphs paula
  dashboard/dashboard.py
  dashboard/pages/subscribe.py
  dashboard/requirements.txt
  dashboard/sl_queries.py
Labels: enhancement, feature

#105 Implemented an upload script
  load_to_rds/README.md
  load_to_rds/clear_database.sh
  load_to_rds/connect.sh
  load_to_rds/delete.sql
  load_to_rds/get_data_from_database.py
  load_to_rds/requirements.txt
  load_to_rds/test_load_to_rds.py
  load_to_rds/transform_game_data.py
  load_to_rds/upload_to_db.py
  schema/schema.sql
Labels: feature

#108 Fixed a bug with the gog scraper.
  web_scraping/gog_scraper/lambda_handler.py
Labels: bug

#106 Report Generation - PR
  report/Dockerfile
  report/database_handler.py
  report/email_report.py
  report/generate_report.py
  report/lambda_handler.py
  report/push-to-ecr.sh
  report/requirements.txt
Labels: feature

#113 PR - Generate Report
  report/README.md
  report/email_report.py
  report/requirements.txt
Labels: documentation, enhancement

#114 Dashboard with almost all of the graphs
  dashboard/.streamlit/config.toml
  dashboard/dashboard.py
  dashboard/functions.py
  dashboard/pages/Games.py
  dashboard/requirements.txt
  dashboard/sl_queries.py
Labels: enhancement, feature

#119 Extract epic GraphQL - Leon
  web_scraping/epic_games_scraper/Dockerfile
  web_scraping/epic_games_scraper/README.md
  web_scraping/epic_games_scraper/extract_epic.py
  web_scraping/epic_games_scraper/lambda_handler.py
  web_scraping/epic_games_scraper/push-to-ecr.sh
  web_scraping/epic_games_scraper/query.graphql
  web_scraping/epic_games_scraper/requirements.txt
  web_scraping/epic_games_scraper/test_epic_games.py
  web_scraping/epic_games_scraper/test_extract_epic.py
  web_scraping/steam_scraper/test_scrape_steam.py
Labels: bug, documentation, enhancement, feature

#126 PR - Report generate
  report/Dockerfile
  report/email_report.py
  report/generate_report.py
  report/lambda_handler.py
  report/report_style
  report/requirements.txt
Labels: enhancement

#125 Subscribe page layout
  dashboard/Dashboard.py
  dashboard/functions.py
  dashboard/pages/About.py
  dashboard/pages/Subscribe.py
  dashboard/pages/subscribe.py
Labels: bug, feature

#121 Wrote a script that creates SNS topics for each base genre.
  load_to_rds/.gitignore
  load_to_rds/Dockerfile
  load_to_rds/create_sns_topics.py
  load_to_rds/create_temp_topic_message.py
  load_to_rds/create_topic_message.py
  load_to_rds/dockerise.sh
  load_to_rds/lambda_handler.py
  load_to_rds/requirements.txt
  load_to_rds/update_sns_topics.py
  load_to_rds/upload_to_db.py
Labels: feature

#136 Added default false field for epic nsfw.
  web_scraping/epic_games_scraper/extract_epic.py
Labels: enhancement

#133 Changes the point at which things get json dumped.
  web_scraping/gog_scraper/lambda_handler.py
Labels: bug

#139 Terraform step function
  terraform/README.md
  terraform/main.tf
Labels: enhancement

#138 Updated Steam NSFW tagging.
  web_scraping/steam_scraper/scrape_steam.py
Labels: enhancement

#143 Added a NSFW detector on the scraper side.
  web_scraping/gog_scraper/scrape_gog_game.py
Labels: feature

#144 Dashboard subscribing
  dashboard/Dashboard.py
  dashboard/functions.py
  dashboard/pages/About.py
  dashboard/pages/Games.py
  dashboard/pages/Subscribe.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/sl_queries.py
Labels: enhancement, feature

#149 Increase coverage for extract scripts.
  web_scraping/epic_games_scraper/test_extract_epic.py
  web_scraping/steam_scraper/test_scrape_steam.py
Labels: test

#150 Added SES.
  load_to_rds/create_html_message.py
  load_to_rds/email_subscribers.py
  load_to_rds/get_subscriber_emails.py
  load_to_rds/lambda_handler.py
  load_to_rds/update_sns_topics.py
Labels: feature

#159 Dashboard README
  dashboard/Dashboard.py
  dashboard/README.md
  dashboard/pages/Subscribe.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/wireframe_about.png
  dashboard/wireframe_dashboard.png
  dashboard/wireframe_games.png
  dashboard/wireframe_subscribe.png
Labels: documentation

#161 Dashboard testing
  dashboard/README.md
  dashboard/functions.py
  dashboard/pages/Subscribe.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/pages/utils/test_subscribe_functions.py
  dashboard/push_to_ecr.sh
  dashboard/sl_queries.py
  dashboard/test_dashboard.py
  dashboard/test_functions.py
  dashboard/test_sl_queries.py
Labels: feature

#158 Load ses mehrdad
  load_to_rds/Dockerfile
  load_to_rds/README.md
  load_to_rds/create_html_message.py
  load_to_rds/create_topic_message.py
  load_to_rds/email_subscribers.py
  load_to_rds/get_subscriber_emails.py
  load_to_rds/lambda_handler.py
  load_to_rds/update_sns_topics.py
  load_to_rds/upload_to_db.py
Labels: bug, feature

#162 Extract increase coverage
  web_scraping/gog_scraper/scrape_gog.py
  web_scraping/gog_scraper/scrape_gog_game.py
  web_scraping/gog_scraper/test_scrape_gog.py
Labels: test

#167 Dashboard testing paula
  dashboard/functions.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/sl_queries.py
Labels: enhancement

#168 Fixed bug - Extract Epic
  web_scraping/epic_games_scraper/extract_epic.py
  web_scraping/epic_games_scraper/test_extract_epic.py
Labels: bug, enhancement

#172 Added sorting to table
  dashboard/functions.py
  dashboard/pages/Games.py
  dashboard/test_functions.py
Labels: enhancement

#165 Dashboard deploy to cloud michael
  dashboard/Dashboard.py
  dashboard/Dockerfile
  dashboard/functions.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/pages/utils/test_subscribe_functions.py
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: documentation

#176 Graph parametres fixed
  dashboard/Dashboard.py
  dashboard/functions.py
  dashboard/sl_queries.py
  dashboard/test_sl_queries.py
Labels: bug

#180 fixed
  dashboard/pages/Subscribe.py
Labels: bug

#179 Caching timeout
  dashboard/Dashboard.py
  dashboard/pages/utils/subscribe_functions.py
  dashboard/sl_queries.py
Labels: enhancement

#183 Stopwords and sorting language
  dashboard/Dashboard.py
  dashboard/functions.py
  dashboard/pages/Games.py
  dashboard/sl_queries.py
  dashboard/test_functions.py
Labels: enhancement

#177 Simplified the lambda handler to always use now().
  web_scraping/steam_scraper/lambda_handler.py
Labels: bug, enhancement

#186 Changed date
  dashboard/Dashboard.py
  dashboard/pages/Games.py
Labels: enhancement

#191 Extract gog mehrdad
  web_scraping/gog_scraper/scrape_gog.py
Labels: bug

#188 Bug fix with Mac OS.
  web_scraping/epic_games_scraper/extract_epic.py
  web_scraping/epic_games_scraper/test_extract_epic.py
Labels: bug

#193 Hiding emails by adding recepients to BCC.
  load_to_rds/email_subscribers.py
Labels: bug

#199 Added instructions to add a new scraper.
  web_scraping/README.md
Labels: documentation

#200 Added a logger for datetime formatter.
  web_scraping/gog_scraper/scrape_gog_game.py
Labels: documentation

#201 Dashboard wordcloud + game count + tooltip improvements
  dashboard/Dashboard.py
  dashboard/functions.py
  dashboard/sl_queries.py
  dashboard/test_sl_queries.py
Labels: enhancement

#203 Added a new line to scraping README.
  web_scraping/README.md
Labels: documentation
